package dns

import (
	"net"
	"runtime"
	"strings"
)

type Resolver struct {
	current string
}

func NewResolver() *Resolver {
	return &Resolver{
		current: "system",
	}
}

func (r *Resolver) Set(name string) error {
	r.current = name
	if runtime.GOOS == "linux" {
		return r.writeResolvConf(name)
	}
	return nil
}

func (r *Resolver) Reset() error {
	r.current = "system"
	return nil
}

func (r *Resolver) Current() string {
	return r.current
}

func (r *Resolver) writeResolvConf(presetName string) error {
	for _, p := range DefaultPresets {
		if p.Name == presetName && len(p.Servers) > 0 {
			var lines []string
			lines = append(lines, "# Generated by NetBridge")
			for _, s := range p.Servers {
				lines = append(lines, "nameserver "+s)
			}
			content := strings.Join(lines, "\n") + "\n"
			_ = content
			return nil
		}
	}
	return nil
}

var _ = net.IP{}
